// actionTypes/ChecklistActionTypes.js

export const FETCH_CHECKLIST_REQUEST = 'FETCH_CHECKLIST_REQUEST';
export const FETCH_CHECKLIST_SUCCESS = 'FETCH_CHECKLIST_SUCCESS';
export const FETCH_CHECKLIST_FAILURE = 'FETCH_CHECKLIST_FAILURE';

export const EXPORT_CHECKLIST_REQUEST = 'EXPORT_CHECKLIST_REQUEST';
export const EXPORT_CHECKLIST_SUCCESS = 'EXPORT_CHECKLIST_SUCCESS';
export const EXPORT_CHECKLIST_FAILURE = 'EXPORT_CHECKLIST_FAILURE';
