export const GET_MATERIAL_REQUEST = 'GET_MATERIAL_REQUEST';
export const GET_MATERIAL_SUCCESS = 'GET_MATERIAL_SUCCESS';
export const GET_MATERIAL_FAILURE = 'GET_MATERIAL_FAILURE';


export const GET_MATERIALTYPE_REQUEST = 'GET_MATERIALTYPE_REQUEST';
export const GET_MATERIALTYPE_SUCCESS = 'GET_MATERIALTYPE_SUCCESS';
export const GET_MATERIALTYPE_FAILURE = 'GET_MATERIALTYPE_FAILURE';

export const GET_MATERIALREQUEST_REQUEST = 'GET_MATERIALREQUEST_REQUEST';
export const GET_MATERIALREQUEST_SUCCESS = 'GET_MATERIALREQUEST_SUCCESS';
export const GET_MATERIALREQUEST_FAILURE = 'GET_MATERIALREQUEST_FAILURE';


export const CREATE_MATERIAL_REQUEST = 'CREATE_MATERIAL_REQUEST';
export const CREATE_MATERIAL_SUCCESS = 'CREATE_MATERIAL_SUCCESS';
export const CREATE_MATERIAL_FAILURE = 'CREATE_MATERIAL_FAILURE';

export const UPDATE_MATERIAL_REQUEST = 'UPDATE_MATERIAL_REQUEST';
export const UPDATE_MATERIAL_SUCCESS = 'UPDATE_MATERIAL_SUCCESS';
export const UPDATE_MATERIAL_FAILURE = 'UPDATE_MATERIAL_FAILURE';

export const UPDATE_MATERIALREQUEST_REQUEST = 'UPDATE_MATERIALREQUEST_REQUEST';
export const UPDATE_MATERIALREQUEST_SUCCESS = 'UPDATE_MATERIALREQUEST_SUCCESS';
export const UPDATE_MATERIALREQUEST_FAILURE = 'UPDATE_MATERIALREQUEST_FAILURE';

export const DELETE_MATERIAL_REQUEST = 'DELETE_MATERIAL_REQUEST';
export const DELETE_MATERIAL_SUCCESS = 'DELETE_MATERIAL_SUCCESS';
export const DELETE_MATERIAL_FAILURE = 'DELETE_MATERIAL_FAILURE';

